### PR TITLE
feature/ipv6 support

### PR DESCRIPTION
**Pull request by mdavis332**
First pass at adding ipv6 support to blocking/queue and blocking/processor. Could use some thorough testing.

### CODE REVIEW

**Comment by Jc2k** [comment]
Cheers @mdavis332 :-) Are you using `hpfeeds.blocking` in something interesting? Is it working for you? I have to be honest, I can't remember finishing that client. It was meant to be a cleanup of `hpfeeds/client.py` but i'm not sure it was much better in the end. If people are happy with it and using it i'm happy to accept patches for it though!

**Comment by mdavis332** [comment]
> Cheers @mdavis332 :-) Are you using `hpfeeds.blocking` in something interesting? Is it working for you? I have to be honest, I can't remember finishing that client. It was meant to be a cleanup of `hpfeeds/client.py` but i'm not sure it was much better in the end. If people are happy with it and using it i'm happy to accept patches for it though!

I don't actually think so. I've been contributing to the [https://github.com/CommunityHoneyNetwork](https://github.com/CommunityHoneyNetwork) project and went on a 'support ipv6' tear today. CHN doesn't look to do anything with `hpfeeds.blocking`, but I just hit everything in the repo I saw with some ipv6 love, then tried to do the same thing for the upstream projects (hpfeeds included).

**Comment by Jc2k** [comment]
Cheers again @mdavis332. Hadn't heard of that project so thank you for bringing it to my attention. As you [can see](https://github.com/CommunityHoneyNetwork/hpfeeds3/issues/2) i've opened an issue to discuss how we can work more closely on hpfeeds. Ideally there shouldn't need to be a fork, I hope we can find a way to work together and minimize the delta.

Meanwhile, how do you want to proceed with this PR? If you aren't using this `hpfeeds.blocking` code in your project them i'm inclined to officially deprecate it and then remove it rather than take this PR. How does that sound to you?

**Comment by mdavis332** [comment]
> Meanwhile, how do you want to proceed with this PR? If you aren't using this `hpfeeds.blocking` code in your project them i'm inclined to officially deprecate it and then remove it rather than take this PR. How does that sound to you?

You've got my vote. While the CHN fork folks don't appear to be using `hpfeeds.blocking` (outside some docs and tests that may just be part of your repo), hopefully they'll have a chance to chat with you on the Issue about whether they use blocking and other overall cohesiveness.

**Comment by Jc2k** [comment]
I've not heard back from the CHN folks, but i'm going to go ahead and close this and remove hpfeeds.blocking.

Thanks for contributing this though.

**Pull request closed without merging**
